name: AnarchyStats
version: ${project.version}
main: lol.hyper.anarchystats.AnarchyStats
api-version: 1.21
load: STARTUP
author: hyperdefined
website: https://github.com/hyperdefined/AnarchyStats
description: Get server age, total players, and world size in a nice little command.
folia-supported: true
permissions:
  anarchystats.reload:
    default: op
    description: Allows the usage of /anarchystats reload
commands:
  anarchystats:
    usage: /anarchystats