name: Update Modrinth Description
on:
  push:
    branches: [ master ]
jobs:
  modrinth-desc:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
      - uses: funnyboy-roks/modrinth-auto-desc@v1.6
        with:
          auth-token: ${{ secrets.MODRINTH }}
          slug: 'Z04RmeT7'